---
- name: Remove k3s
  ansible.builtin.command:
    cmd: bash /opt/setup/uninstall_k3s.sh
  become: true

- name: Update/Upgrade apt archives
  ansible.builtin.apt:
    update_cache: yes
    upgrade: "yes"
    cache_valid_time: 86400
  become: true

- name: Install podman
  ansible.builtin.apt:
    name: "podman"
    state: present
  become: true

- name: Install podman-compose
  ansible.builtin.apt:
    name: "podman-compose"
    state: present
  become: true

- name: Render podman registries
  ansible.builtin.template:
    src: podman_registries.j2
    dest: /etc/containers/registries.conf.d/cr.lab.local.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Restart podman Service