---
- name: Remove podman
  ansible.builtin.apt:
    name: "podman"
    state: absent
  become: true

- name: Remove podman-compose
  ansible.builtin.apt:
    name: "podman-compose"
    state: absent
  become: true

- name: Install k3s
  ansible.builtin.command:
    cmd: bash /opt/setup/install_k3s.sh
  become: true

- name: Render k3s registries
  ansible.builtin.template:
    src: k3s_registries.j2
    dest: /etc/rancher/k3s/registries.yaml
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Restart k3s Service

# - name: Install Cilium
#   ansible.builtin.command:
#     cmd: /opt/setup/install_cilium.sh
#   become: true

# - name: Install Gateway API
#   ansible.builtin.command:
#     cmd: /opt/setup/install_gateway_api.sh
#   become: true
