---
# tasks file for student
- name: Install software
  ansible.builtin.include_tasks: install_packages.yml
  when:
    - install_packages

- name: Enable password authentication
  ansible.builtin.include_tasks: enable_pw_auth.yml
  when:
    - enable_pw_auth

- name: Copy setup scripts
  ansible.builtin.include_tasks: copy_setup_scripts.yml
  when:
    - copy_setup_scripts

- name: Install k3s
  ansible.builtin.include_tasks: install_k3s.yml
  when:
    - install_k3s

- name: Install Oh My Zsh
  ansible.builtin.include_tasks: install_oh_my_zsh.yml
  when:
    - install_oh_my_zsh

- name: Rsync lab file
  ansible.builtin.include_tasks: rsync_lab_files.yml
  when:
    - rsync_lab_files
