apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: splunk
  namespace: splunk
data:
  default.yml: |
    ---
    splunk:
      hec:
        enable: True
        ssl: False
        port: 8088
        token: abcd1234

