apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        name: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        envFrom:
        - secretRef:
            name: postgres
        volumeMounts:
        - name: guacamole-init-db
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: guacamole-init-db
        configMap:
          name: guacamole-init-db
          items:
          - key: initdb.sql
            path: initdb.sql
          - key: z_create-auth.sql
            path: z_create-auth.sql
