version: '3.7'
# networks
networks:
  guacnet:
    driver: bridge

# services
services:
  guacd:
    container_name: guac_guacd
    image: guacamole/guacd
    networks:
      guacnet:
    restart: always

  postgres:
    container_name: guac_postgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChangeThisPassword'
      POSTGRES_USER: guacamole_user
    image: postgres:13
    networks:
      guacnet:
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./data:/var/lib/postgresql/data:rw

  guacamole:
    container_name: guac_guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChangeThisPassword'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
      - guacd
    networks:
      guacnet:
    ports:
      - 8080:8080/tcp
    restart: always