---
- name: Delete docker gpg if exists
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    state: absent
  become: yes

- name: Copy docker install script
  ansible.builtin.copy:
    src: ../files/docker_install.sh
    dest: /tmp/docker_install.sh
    mode: '0755'
  
- name: Execute install script
  ansible.builtin.command:
    cmd: /tmp/docker_install.sh
  become: yes
