apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-80
  namespace: kcd
spec:
  podSelector:
    matchLabels:
      project: kcd
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: 80