apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: guacamole-ingress
  namespace: guacamole
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: HostRegexp(`{host:.+}`)
      services:
        - kind: Service
          name: guacamole
          port: 80
