apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kcd-web
  name: kcd-web
  namespace: kcd
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: web
status:
  loadBalancer: {}