apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: splunk-ingress
  namespace: splunk
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/`)
      services:
        - kind: Service
          name: splunk
          port: 8000
