---
- name: Set ZSH as default shell
  ansible.builtin.user:
    name: student
    shell: /bin/zsh
  become: yes

- name: Download Oh My Zsh install script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /opt/setup/install_oh-my-zsh.sh
    mode: '0755'
  become: yes

- name: Remove global directory if it exists already
  ansible.builtin.file:
    path: /opt/ohmyzsh
    state: absent
  become: yes

- name: Install Oh My Zsh into the global directory
  environment:
    ZSH: /opt/ohmyzsh
  ansible.builtin.command:
    cmd: sh /opt/setup/install_oh-my-zsh.sh --unattended
  become: yes

- name: Copy .zshrc
  ansible.builtin.copy:
    src: ../files/.zshrc
    dest: /home/student/
    owner: student
    group: student
    mode: '0644'
  become: yes