---
- name: Copy guacamole install script
  ansible.builtin.copy:
    src: ../files/config_guacamole.sh
    dest: /opt/setup/config_guacamole.sh
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Register postgrest service IP
  ansible.builtin.command:
    cmd: kubectl get svc postgrest -n guacamole -o jsonpath='{.spec.clusterIP}'
  register: postgrest_ip

- name: Register postgrest service port
  ansible.builtin.command:
    cmd: kubectl get svc postgrest -n guacamole -o jsonpath='{.spec.ports[0].port}'
  register: postgrest_port

- name: Wait until HTTP status is 200
  ansible.builtin.uri:
    url: 'http://{{ postgrest_ip.stdout }}:{{ postgrest_port.stdout }}'
    return_content: yes
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 10 # Retries for 10 * 2 seconds
  delay: 2 # Every 2 seconds
  register: uri_output

- name: Execute guacamole install script
  ansible.builtin.command:
    cmd: bash /opt/setup/config_guacamole.sh
  become: yes
