---
- name: Remove guacamole config files
  ansible.builtin.file:
    path: /opt/setup/guacamole
    state: absent
  become: yes

- name: Create directory for guacamole config files
  ansible.builtin.file:
    path: /opt/setup/guacamole
    state: directory
    mode: '0755'
  become: yes

- name: Initialize an empty list for IP addresses
  set_fact:
    lab_ips: []

- name: Add each host's IP to the list
  set_fact:
    lab_ips: "{{ lab_ips + [hostvars[item]['ansible_host'] | default(item)] }}"
  loop: "{{ groups['lab'] }}"

- name: Create salt and password hash
  ansible.builtin.command:
    argv:
      - python
      - ../bastion/files/gen_guac_hash.py
      - "{{ guacamole_pw }}"
  delegate_to: localhost
  run_once: yes
  register: hash_script_output

- name: Parse script output into multiple facts
  set_fact:
    guac_hashes: "{{ guac_hashes | default({}) | combine({ item.split('=')[0]: item.split('=')[1] }) }}"
  with_items: "{{ hash_script_output.stdout_lines }}"

- name: Display Guacamole hashes
  debug:
    var: guac_hashes

- name: Render entity json
  become: yes
  ansible.builtin.template:
    src: guac_entity.j2
    dest: /opt/setup/guacamole/guac_entity.json
    owner: root
    group: root
    mode: '0644'

- name: Render user group json
  become: yes
  ansible.builtin.template:
    src: guac_user_group.j2
    dest: /opt/setup/guacamole/guac_user_group.json
    owner: root
    group: root
    mode: '0644'

- name: Render user json
  become: yes
  ansible.builtin.template:
    src: guac_user.j2
    dest: /opt/setup/guacamole/guac_user.json
    owner: root
    group: root
    mode: '0644'

- name: Render connection group json
  become: yes
  ansible.builtin.template:
    src: guac_connection_group.j2
    dest: /opt/setup/guacamole/guac_connection_group.json
    owner: root
    group: root
    mode: '0644'

- name: Render connection json
  become: yes
  ansible.builtin.template:
    src: guac_connection.j2
    dest: /opt/setup/guacamole/guac_connection.json
    owner: root
    group: root
    mode: '0644'

- name: Render connection parameter json
  become: yes
  ansible.builtin.template:
    src: guac_connection_parameter.j2
    dest: /opt/setup/guacamole/guac_connection_parameter.json
    owner: root
    group: root
    mode: '0644'

- name: Render connection permission json
  become: yes
  ansible.builtin.template:
    src: guac_connection_permission.j2
    dest: /opt/setup/guacamole/guac_connection_permission.json
    owner: root
    group: root
    mode: '0644'

- name: Render connection group permission json
  become: yes
  ansible.builtin.template:
    src: guac_connection_group_permission.j2
    dest: /opt/setup/guacamole/guac_connection_group_permission.json
    owner: root
    group: root
    mode: '0644'

