---
- name: Set alive interval
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^#ClientAliveInterval\s+\d+'
    replace: 'ClientAliveInterval 0'
  become: yes

- name: Set alive count
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^#ClientAliveCountMax\s+\d+'
    replace: 'ClientAliveCountMax 1000'
  become: yes

- name: Restart sshd service
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: yes