---
# tasks file for bastion
- name: Install software
  ansible.builtin.include_tasks: install_packages.yml
  when:
    - install_packages

- name: Copy nginx config file
  ansible.builtin.include_tasks: copy_nginx_config.yml
  when:
    - copy_nginx_config

- name: Configure haproxy
  ansible.builtin.include_tasks: configure_haproxy.yml
  when:
    - configure_haproxy

- name: Enable password authentication
  ansible.builtin.include_tasks: enable_pw_auth.yml
  when:
    - configure_sshd

- name: Disable SSH timeout
  ansible.builtin.include_tasks: disable_ssh_timeout.yml
  when:
    - configure_sshd