---
# tasks file for bastion
- name: Install additional software
  ansible.builtin.include_tasks: install_additional_packages.yml
  when:
    - install_additional_packages

- name: Setup nginx
  ansible.builtin.include_tasks: setup_nginx.yml
  when:
    - setup_nginx

- name: Rsync setup files
  ansible.builtin.include_tasks: rsync_setup_files.yml
  when:
    - rsync_setup_files

- name: Setup k3s
  ansible.builtin.include_tasks: setup_k3s.yml
  when:
    - setup_k3s

- name: Setup Guacamole
  ansible.builtin.include_tasks: setup_guacamole.yml
  when:
    - setup_guacamole

