---
# tasks file for bastion
- name: Install software
  ansible.builtin.include_tasks: install_packages.yml
  when:
    - install_packages

- name: Copy nginx config file
  ansible.builtin.include_tasks: copy_nginx_config.yml
  when:
    - copy_nginx_config

- name: Create Guacamole configs
  ansible.builtin.include_tasks: create_guac_configs.yml
  when:
    - create_guac_configs

- name: Configure Guacamole
  ansible.builtin.include_tasks: configure_guacamole.yml
  when:
    - configure_guacamole

- name: Rsync setup files
  ansible.builtin.include_tasks: rsync_setup_files.yml
  when:
    - rsync_setup_files

- name: Install k3s
  ansible.builtin.include_tasks: install_k3s.yml
  when:
    - install_k3s