---
- name: Initialize an empty list for lab host IP addresses
  set_fact:
    lab_ips: []

- name: Add each host's IP to the list
  set_fact:
    lab_ips: "{{ lab_ips + [hostvars[item]['ansible_host'] | default(item)] }}"
  loop: "{{ groups['lab'] }}"

- name: Render nginx config
  become: yes
  ansible.builtin.template:
    src: nginx_config.j2
    dest: /etc/nginx/conf.d/training.conf
    owner: root
    group: root
    mode: '0644'

- name: Delete default site
  become: yes
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - Restart nginx Service
