---
- name: Remove setup files
  ansible.builtin.file:
    path: /opt/setup
    state: absent
  become: yes

- name: Create setup directory
  ansible.builtin.file:
    path: /opt/setup
    state: directory
    mode: '0755'
  become: yes

- name: Copy k3s yaml files
  ansible.posix.synchronize:
    src: ../files/k3s
    dest: /opt/setup
  become: yes

- name: Render ingress config
  become: yes
  ansible.builtin.template:
    src: ingress.j2
    dest: /opt/setup/k3s/ingress/ingress.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart nginx Service

- name: Copy k3s install script
  ansible.builtin.copy:
    src: ../files/setup_k3s.sh
    dest: /opt/setup/setup_k3s.sh
    mode: '0644'
  become: yes

- name: Copy guacamole install script
  ansible.builtin.copy:
    src: ../files/setup_guacamole.sh
    dest: /opt/setup/setup_guacamole.sh
    mode: '0644'
  become: yes

- name: Copy guacamole config script
  ansible.builtin.copy:
    src: ../files/config_guacamole.sh
    dest: /opt/setup/config_guacamole.sh
    mode: '0644'
  become: yes

- name: Change folder permissions
  ansible.builtin.file:
    path: /opt/setup
    state: directory
    recurse: yes
    owner: root
    group: root
  become: yes


