---
- name: Copy k3s yaml files
  ansible.posix.synchronize:
    src: ../files/k3s
    dest: /opt/setup
  become: true

- name: Setup k3s
  ansible.builtin.command:
    cmd: bash /opt/setup/setup_k3s.sh
  become: true

- name: Wait for k3s to be ready
  ansible.builtin.wait_for:
    port: 6443
    delay: 5
