kubeProxyReplacement: true
gatewayAPI:
  enabled: true
hostNetwork:
  enabled: true
l2announcements:
  enabled: false
externalIPs:
  enabled: false
k8sClientRateLimit:
  qps: 50
  burst: 200
operator:
  replicas: 1
  rollOutPods: true
rollOutCiliumPods: true
ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared