---
# defaults file for bastion
install_packages: False
setup_nginx: False
create_guac_configs: False
configure_guacamole: False
rsync_setup_files: False
setup_environment: False
setup_k3s: False
setup_guacamole: False