---
- name: Enable pasword authentication
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication\s+\w+'
    replace: 'PasswordAuthentication yes'
  become: yes

- name: Restart sshd service
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: yes