---
# tasks file for student
- name: Install software
  ansible.builtin.include_tasks: install_packages.yml
  when:
    - install_packages

- name: Install docker
  ansible.builtin.include_tasks: install_docker.yml
  when:
    - install_docker

- name: Add user to docker group
  ansible.builtin.include_tasks: add_user_docker.yml
  when:
    - install_docker

- name: Enable password authentication
  ansible.builtin.include_tasks: enable_pw_auth.yml
  when:
    - enable_pw_auth

- name: Copy lab files
  ansible.builtin.include_tasks: rsync_lab_files.yml
  when:
    - copy_lab_files