---
- name: Update/Upgrade apt archives
  ansible.builtin.apt:
    update_cache: yes
    upgrade: "yes"
    cache_valid_time: 86400
  become: true

- name: Install software packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}" 
  become: true