---
- name: Download Splunk OTEL collector
  ansible.builtin.get_url:
    url: https://dl.signalfx.com/splunk-otel-collector.sh
    dest: /opt/setup/splunk-otel-collector.sh
    mode: '0755'
  become: true

- name: Install Oh My Zsh into the global directory
  environment:
    ZSH: /opt/ohmyzsh
  ansible.builtin.command:
    cmd: sh /opt/setup/splunk-otel-collector.sh --realm eu0 --memory $SPLUNK_MEMORY_TOTAL_MIB -- $SPLUNK_ACCESS_TOKEN
  become: true