---
- name: Generate OTEL basic config
  become: true
  ansible.builtin.template:
    src: otel-base.j2
    dest: /etc/otelcol-contrib/config.yaml
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart OTEL Collector

 # sudo apt install acl
 # sudo usermod -a -G systemd-journal otelcol-contrib
 # sudo setfacl -m otelcol-contrib:r-- /var/log/auth.log
 # sudo setfacl -m otelcol-contrib:r-- /var/log/syslog
...