all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_aws_ansible
  children:
    bastion:
      hosts:
        ec2-52-208-54-82.eu-west-1.compute.amazonaws.com:
    student:
      hosts:
        10.42.22.27:
        10.42.22.9:
        10.42.22.16:
    lab:
      hosts:

        