apiVersion: v1
kind: Service
metadata:
  name: postgrest
  namespace: guacamole
spec:
  selector:
    app: postgrest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
