apiVersion: v1
data:
  PGRST_DB_ANON_ROLE: YW5vbg==
  PGRST_DB_URI: cG9zdGdyZXM6Ly9hdXRoZW50aWNhdG9yOmF1dGhlbnRpY2F0b3JAcG9zdGdyZXMuZ3VhY2Ftb2xlLnN2Yy5jbHVzdGVyLmxvY2FsOjU0MzIvZ3VhY2Ftb2xl
kind: Secret
metadata:
  creationTimestamp: null
  name: postgrest
  namespace: guacamole
