apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
  namespace: guacamole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
